In [1]:
import numpy as np
import torch

In [2]:
t = torch.FloatTensor([0,1,2,3,4,5,6])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [5]:
print(t.dim())
print(t.shape) # shape
print(t.size())# shape

1
torch.Size([7])
torch.Size([7])


In [8]:
t = torch.FloatTensor([ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [14]:
print(t.dim())
print(t.size())
print(t[:,1])
print(t[:,1].size())
print(t[:,:-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting

In [16]:
# same shape
m1 = torch.FloatTensor([[3 ,3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1.size(), m2.size())
print(m1 + m2)

torch.Size([1, 2]) torch.Size([1, 2])
tensor([[5., 5.]])


In [17]:
# vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[4., 5.]])


In [18]:
# 2X 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### View (Reshape)

In [19]:
t = np.array([[[0,1,2],
               [3,4,5]],
                
              [[6,7,8],
               [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.size())

torch.Size([2, 2, 3])


In [20]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).size())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [21]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).size())

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze 

In [22]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [23]:
# element 가 1인 곳을 제거
print(ft.squeeze())
print(ft.squeeze().size())

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze

In [24]:
# 원하는 dim 을 명시해줘야한다
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [25]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [26]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [27]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [28]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Type Casting

In [29]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [30]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [31]:
bt = torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [32]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenate

In [35]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [36]:
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [37]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [40]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z]).shape)
print()
print(torch.stack([x,y,z], dim=1))
print(torch.stack([x,y,z], dim=1).shape)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


### Ones and Zeros

In [41]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [42]:
# 같은 디바이스에 있는 텐서를 만들어준다.
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [43]:
x = torch.FloatTensor([[1,2],[3,4]])

In [44]:
print(x.mul(2.))
print(x)
# 해당 메모리에 ...
print(x.mul_(2.))
print(x)
# python garbage collector 가 잘 작동하여 속도 향상에 크게 영향을 주지는 않을수있다.

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
